AWS_ACCESS_KEY_ID: Rails.application.credentials[:AWS_ACCESS_KEY_ID]
AWS_SECRET_ACCESS_KEY: Rails.application.credentials[:AWS_SECRET_ACCESS_KEY]
S3_BUCKET_NAME: Rails.application.credentials[:S3_BUCKET_NAME]  
